CREATE PROCEDURE sp_get_admin(@param_USUARIO VARCHAR(100),@param_CONTRASENA VARCHAR(100))
AS
BEGIN
	SELECT [ID]
	, [USUARIO]
	, [CONTRASENA]
	FROM [CORION].[ADMINS]
	WHERE USUARIO=@param_USUARIO AND CONTRASENA=@param_CONTRASENA
END

CREATE PROCEDURE sp_insert_product (@param_NOMBRE VARCHAR(100)
, @param_MARCA VARCHAR(100), @param_PRECIO FLOAT,@param_DIMENSIONES VARCHAR(100),@param_DESCRIPCION VARCHAR(100))
AS
BEGIN
	INSERT INTO CORION.PRODUCTO 
	(NOMBRE,MARCA,PRECIO,DIMENSIONES,DESCRIPCION) 
	VALUES 
	(@param_NOMBRE,@param_MARCA,@param_PRECIO,@param_DIMENSIONES,@param_DESCRIPCION)
END