CREATE PROCEDURE sp_get_admin(@param_USUARIO VARCHAR(100),@param_CONTRASENA VARCHAR(100))
AS
BEGIN
	SELECT [ID]
	, [USUARIO]
	, [CONTRASENA]
	FROM [CORION].[ADMINS]
	WHERE USUARIO=@param_USUARIO AND CONTRASENA=@param_CONTRASENA
END
USE CORION_TOMEYLLEVE_IF6201
CREATE PROCEDURE sp_insert_product (@param_NOMBRE VARCHAR(100)
, @param_MARCA VARCHAR(100), @param_PRECIO FLOAT,@param_DIMENSIONES VARCHAR(100),@param_DESCRIPCION VARCHAR(100),@param_PIMAGE VARCHAR(200))
AS
BEGIN
	INSERT INTO CORION.PRODUCTO 
	(NOMBRE,MARCA,PRECIO,DIMENSIONES,DESCRIPCION,PIMAGE) 
	VALUES 
	(@param_NOMBRE,@param_MARCA,@param_PRECIO,@param_DIMENSIONES,@param_DESCRIPCION,@param_PIMAGE)
END
GO


CREATE PROCEDURE sp_get_allproducts
AS
BEGIN
	SELECT [ID]
	, [NOMBRE]
	, [MARCA]
	, [PRECIO]
	, [DIMENSIONES]
	, [DESCRIPCION]
	FROM [CORION].[PRODUCTO]
END

CREATE PROCEDURE sp_delete_product (@param_ID INT)
AS
BEGIN
	DELETE FROM CORION.PRODUCTO
	WHERE ID=@param_ID
END

CREATE PROCEDURE sp_update_product (@param_ID INT, @param_NOMBRE VARCHAR(100)
, @param_MARCA VARCHAR(100), @param_PRECIO FLOAT,@param_DIMENSIONES VARCHAR(100),@param_DESCRIPCION VARCHAR(100))
AS
BEGIN
	UPDATE CORION.PRODUCTO
	SET NOMBRE=@param_NOMBRE
	, MARCA=@param_MARCA
	, PRECIO=@param_PRECIO
	, DIMENSIONES=@param_DIMENSIONES
	, DESCRIPCION=@param_DESCRIPCION
	WHERE ID=@param_ID
END

CREATE PROCEDURE sp_get_product (@param_ID INT)
AS
BEGIN
	SELECT [ID]
	, [NOMBRE]
	, [MARCA]
	, [PRECIO]
	, [DIMENSIONES]
	, [DESCRIPCION]
	FROM [CORION].[PRODUCTO]
	WHERE ID=@param_ID
END
