USE [IF6201_Tome&Lleve]
GO
CREATE SCHEMA PROVEEDOR
GO
CREATE SCHEMA PRODUCTO
GO
CREATE SCHEMA USUARIO
GO
CREATE SCHEMA FACTURA

CREATE TABLE PROVEEDOR.tb_CLAVE(
IDC INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,CLAVE VARCHAR(250) NOT NULL
)

CREATE TABLE PROVEEDOR.tb_PROVEEDOR(
ID INT PRIMARY KEY NOT NULL IDENTITY(1,1)
,NOMBRE VARCHAR(50) NOT NULL
,IDC INT NULL
,FOREIGN KEY (IDC) REFERENCES PROVEEDOR.tb_CLAVE(IDC)
)

CREATE TABLE PRODUCTO.tb_CATEGORIA(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,CATEGORIA VARCHAR(100) NOT NULL
)

CREATE TABLE PRODUCTO.tb_PRODUCTO(
IDP INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,NOMBREP VARCHAR(250) NOT NULL
,DESCRIPCION VARCHAR(MAX)
,PRECIO INT NOT NULL
,DIMENSION VARCHAR(50) NOT NULL
,OTRASCARACTERISTICAS VARCHAR(200)
,FOTO VARCHAR(220) NOT NULL
,CANTIDAD INT NOT NULL
,ISDELETE BIT NOT NULL
,IDPROVEEDOR INT NOT NULL
,IDCATEGORIA INT NOT NULL
,FOREIGN KEY (IDPROVEEDOR) REFERENCES PROVEEDOR.tb_PROVEEDOR(ID)
,FOREIGN KEY (IDCATEGORIA) REFERENCES PRODUCTO.tb_CATEGORIA(ID)
)



CREATE TABLE USUARIO.tb_TARJETACREDITO(
IDCREDIT INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,NUMERO VARCHAR(50) NOT NULL
,CODIGOSEGURIDAD INT NOT NULL
,TIPO VARCHAR(50) NOT NULL
,FECHAVENCIMIENTO DATE NOT NULL
)

CREATE TABLE USUARIO.tb_USUARIO(
CEDULA INT PRIMARY KEY NOT NULL
,NOMBRE VARCHAR(50) NOT NULL
,APELLIDO VARCHAR(50) NOT NULL
,ALIAS VARCHAR(50) NOT NULL 
,CONTRASENNA VARCHAR(50) NOT NULL
)



CREATE TABLE PRODUCTO.tb_CARRITO(
IDP INT NOT NULL
,IDU INT NOT NULL
,CANTIDAD INT NOT NULL
,CONSTRAINT PK_tb_CARRITO PRIMARY KEY (IDP,IDU)
,FOREIGN KEY (IDP) REFERENCES PRODUCTO.tb_PRODUCTO(IDP)
,FOREIGN KEY (IDU) REFERENCES USUARIO.tb_USUARIO(CEDULA)
)




CREATE TABLE USUARIO.tb_USUARIO_TARJETACREDITO(
CEDULA INT NOT NULL
,IDCREDIT INT NOT NULL
,CONSTRAINT PK_tb_USUARIO_TARJETACREDITO PRIMARY KEY (CEDULA,IDCREDIT)
,FOREIGN KEY (CEDULA) REFERENCES USUARIO.tb_USUARIO(CEDULA)
,FOREIGN KEY (IDCREDIT) REFERENCES USUARIO.tb_TARJETACREDITO(IDCREDIT)
)

CREATE TABLE FACTURA.tb_COMPRA(
IDCOMPRA INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,IDCLIENTE INT NOT NULL
,FECHA DATE NOT NULL
,ID_DIRECCION INT NOT NULL
,IDCREDIT INT NOT NULL
,FOREIGN KEY (IDCLIENTE) REFERENCES USUARIO.tb_USUARIO(CEDULA)
,FOREIGN KEY (ID_DIRECCION) REFERENCES FACTURA.tb_DIRECCION(ID)
,FOREIGN KEY (IDCREDIT) REFERENCES USUARIO.tb_TARJETACREDITO(IDCREDIT)
)

CREATE TABLE FACTURA.tb_DIRECCION(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,PROVINCIA VARCHAR(50) NOT NULL
,CIUDAD VARCHAR(50) NOT NULL
,DETALLE VARCHAR(50) NOT NULL
)


CREATE TABLE FACTURA.tb_DETALLE_FACTURA(
ID_DETALLE INT PRIMARY KEY IDENTITY(1,1) NOT NULL
,IDCOMPRA INT NOT NULL
,IDPRODUCTO INT NOT NULL
,CANTIDAD INT NOT NULL
,MONTO INT NOT NULL
,FOREIGN KEY (IDCOMPRA) REFERENCES FACTURA.tb_COMPRA(IDCOMPRA)
,FOREIGN KEY (IDPRODUCTO) REFERENCES PRODUCTO.tb_PRODUCTO(IDP)
)