USE if6201_caite;

CREATE TABLE tb_PRODUCTO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL
,NOMBRE VARCHAR(50) NOT NULL
,DESCRIPCION VARCHAR(100) NOT NULL
,PRECIO INT NOT NULL
,TALLA INT NOT NULL
,COLOR VARCHAR(50) NOT NULL
,MARCA VARCHAR(50) NOT NULL
,IMAGEN VARCHAR(220) NOT NULL
);

CREATE TABLE tb_CATEGORIA(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL
,NOMBRE VARCHAR(50) NOT NULL
);

CREATE TABLE tb_PRODUCTO_CATEGORIA(
CODIGOP INT NOT NULL
,CODIGOC INT NOT NULL
,CONSTRAINT PK_tb_PRODUCTO_CATEGORIA PRIMARY KEY(CODIGOP,CODIGOC)
,FOREIGN KEY (CODIGOP) REFERENCES if6201_caite.tb_PRODUCTO(ID)
,FOREIGN KEY (CODIGOC) REFERENCES if6201_caite.tb_CATEGORIA(ID)
);